package rms.view.search;

import rms.control.Main;
import rms.control.search.AbstractFinder;
import rms.control.search.TagFinder;
import rms.view.util.JPanelTagSelection;

/**
 * Dialog for selecting a {@link Tag} (for searching)
 * 
 * @author Timothy
 */
public class DialogSearchTags extends BaseDialog {

    private boolean tagChosenSpecial;
    
    /**
     * Creates new form DialogSearchTags
     * @param parent
     */
    public DialogSearchTags(java.awt.Frame parent) {
        super(parent, true);
        tagChosenSpecial = false;
        initComponents();
        initComponentsMore();
    }
    
    @Override
    protected AbstractFinder createFinder() {
        return new TagFinder(jPanelTagSelection.getResult());
    }
    
    private void initComponentsMore(){
        jPanelTagSelection.addItemChosenListener(new JPanelTagSelection.ItemChosenListener(){
            @Override
            public void itemChosen(JPanelTagSelection.ItemChosenEvent m) {
                tagChosenSpecial = true;
                setVisible(false);
            }
        });
    }
    
    @Override
    public AbstractFinder getResult(){
        if(tagChosenSpecial){
            return createFinder();
        }else{
            return super.getResult();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTagSelection = new rms.view.util.JPanelTagSelection(Main.getState().getTags());

        setMinimumSize(new java.awt.Dimension(332, 295));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getInnerContentPanel());
        getInnerContentPanel().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTagSelection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTagSelection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rms.view.util.JPanelTagSelection jPanelTagSelection;
    // End of variables declaration//GEN-END:variables
}
