package rms.view.search;

import java.util.Set;
import rms.control.Main;
import rms.control.search.AbstractFinder;
import rms.control.search.TagFinder;
import rms.model.Tag;
import rms.view.util.JPanelTagSelection;

/**
 * Dialog for selecting one or more {@link Tag}s (for searching)
 *
 * @author Timothy
 */
public class DialogSearchTags extends BaseSearchDialog {

    /**
     * Creates new form DialogSearchTags
     *
     * @param parent
     */
    public DialogSearchTags(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        initComponentsMore();
    }

    @Override
    protected AbstractFinder createFinder() {
        Set<Tag> selectedTags = tagSelectionPanel.getSelectedTags();
        return selectedTags.isEmpty() ? null : new TagFinder(selectedTags);
    }

    private void initComponentsMore() {
        tagSelectionPanel.addDoubleClickSelectionListener(new JPanelTagSelection.DoubleClickSelectionListener() {
            @Override
            public void itemsSelected(JPanelTagSelection.SelectedTags m) {
                hideDialog(false);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tagSelectionPanel = new rms.view.util.JPanelTagSelection(Main.getState().getTagsUnmodifiable());

        setMinimumSize(new java.awt.Dimension(332, 295));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getInnerContentPanel());
        getInnerContentPanel().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tagSelectionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tagSelectionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rms.view.util.JPanelTagSelection tagSelectionPanel;
    // End of variables declaration//GEN-END:variables
}
