package rms.view.item;

import java.io.File;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import rms.model.item.FileItem;
import rms.model.item.Item;
import rms.view.MainFrame;
import rms.view.util.Prompts;

/**
 *
 * @author Timothy
 */
public abstract class FileItemBasePanel extends BaseItemPanel {

    protected static final Logger LOG = Logger.getLogger(FileItemBasePanel.class.getName());

    /**
     * Creates new form {@link FileItemBasePanel}.
     *
     * NOTE: calls {@link #initComponents()}
     *
     * @param item
     * @param startCollapsed
     * @param buttonText
     */
    protected FileItemBasePanel(Item item, boolean startCollapsed, String buttonText) {
        super(item, startCollapsed);
        initComponents();
        setFileButtonText(buttonText);
//        jButtonFileLink.setBorderPainted(true);
//        rms.util.Helpers.addOutsideColorBorder(jButtonFileLink, java.awt.Color.GREEN);
    }

    protected final void setFileButtonText(String newText) {
        jButtonFileLink.setText(newText);
        jButtonFileLink.setToolTipText(newText);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonFileLink = new javax.swing.JButton();

        getInnerContentPanel().setLayout(new javax.swing.BoxLayout(getInnerContentPanel(), javax.swing.BoxLayout.X_AXIS));

        jButtonFileLink.setForeground(new java.awt.Color(0, 0, 255));
        jButtonFileLink.setText("Open File");
        jButtonFileLink.setBorderPainted(false);
        jButtonFileLink.setContentAreaFilled(false);
        jButtonFileLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonFileLink.setFocusPainted(false);
        jButtonFileLink.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFileLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFileLinkActionPerformed(evt);
            }
        });
        getInnerContentPanel().add(jButtonFileLink);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFileLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFileLinkActionPerformed
        fileButtonAction();
    }//GEN-LAST:event_jButtonFileLinkActionPerformed

    /**
     * Executed when the file name button is clicked.
     */
    protected abstract void fileButtonAction();

    /**
     * Executed when the Auxiliary button is clicked. Prompts the user for a new
     * file and replaces the existing {@link Item} with a new {@link FileItem}.
     */
    @Override
    protected void auxiliaryButtonAction() {
        //Prompt the user for the new file. If a selection is made, then
        //  replace the existing item with a new FileItem in the current
        //  thread and force the GUI to redraw.
        MainFrame gui = MainFrame.instance();
        List<File> selection = gui.promptFileSelection(false);//single selection
        if (!selection.isEmpty()) {
            if (selection.size() > 1) {
                LOG.log(Level.WARNING, "Somehow multiple files were selected! Using only the first.");
            }
            FileItem.CreateResult result = FileItem.createAndReplaceFileItem(displayedItem, selection.get(0));
            if (result.success()) {
                deleteButtonAction_WithApproval();//if there was a file, delete it
                gui.refreshSelectedThread();//no need to refresh if no selection
            } else {
                Prompts.informUser("File Import Failed", result.error, Prompts.PromptType.ERROR);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFileLink;
    // End of variables declaration//GEN-END:variables
}
