package rms.view.item;

import rms.model.item.NoteItem;

/**
 *
 * @author Timothy
 */
public class NoteItemPanel extends BaseItemPanel {

    /**
     * Creates a new {@link NoteItemPanel} displaying the given
     * {@link NoteItem}.
     *
     * @param item
     * @param startCollapsed
     */
    public NoteItemPanel(NoteItem item, boolean startCollapsed) {
        super(item, startCollapsed);
        initComponents();

        //register a listener to update the underlying item content and 
        //  modification time when the text changes in the UI.
        itemTextField.addItemTextUpdateListener(new EditableTextField.ItemTextUpdateListener() {
            @Override
            public void textUpdated(EditableTextField.ItemTextUpdatedEvent evt) {
                if (getNoteItem().replaceText(evt.getNewText())) {
                    updateUI_modTime();
                }
            }
        });
    }

    private NoteItem getNoteItem() {
        return (NoteItem) displayedItem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemTextField = new rms.view.item.EditableTextField(getNoteItem().getText(), super.getAuxButton());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getInnerContentPanel());
        getInnerContentPanel().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(itemTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(itemTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rms.view.item.EditableTextField itemTextField;
    // End of variables declaration//GEN-END:variables
}
