package rms.view.item;

import java.awt.Container;
import java.awt.Desktop;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import rms.model.item.FileItem;
import rms.view.util.Prompts;

/**
 * Panel for displaying a {@link FileItem}
 * 
 * @author Timothy
 */
public class PanelFileItem extends javax.swing.JPanel {
    
    private static final Logger thisLog = Logger.getLogger(PanelFileItem.class.getName());

    private final FileItem item;

    /**
     * Creates new form PanelNoteItem
     * @param itm
     */
    public PanelFileItem(FileItem itm) {
        initComponents();
        
        item = itm;
        
        reflectItemChanges();
    }
    
        
    private void reflectItemChanges(){
        jLabelID.setText(String.format("%05d", item.getID()));
        jLabelDateCreated.setText(item.getCreationTime().toString());
        jLabelDateModified.setText(item.getModificationTime().toString());
        jButtonFileLink.setText(item.getFile().getName());
    }
    
    
    private void deleteItem(){
        item.getThread().remove(item);
        //cheap way to update UI
        Container p = this.getParent();
        p.remove(this);
        p.revalidate();
        p.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelType = new javax.swing.JLabel();
        jLabelDateCreated = new javax.swing.JLabel();
        jButtonDelete = new javax.swing.JButton();
        jLabelCreated = new javax.swing.JLabel();
        jLabelModified = new javax.swing.JLabel();
        jLabelDateModified = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jButtonFileLink = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(345, 95));

        jLabelType.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelType.setText("File Import:");

        jLabelDateCreated.setText("Date");

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jLabelCreated.setText("Imported:");

        jLabelModified.setText("Modified:");

        jLabelDateModified.setText("Date");

        jLabelID.setText("00000");

        jButtonFileLink.setForeground(new java.awt.Color(0, 0, 255));
        jButtonFileLink.setText("Open File");
        jButtonFileLink.setBorderPainted(false);
        jButtonFileLink.setContentAreaFilled(false);
        jButtonFileLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonFileLink.setFocusPainted(false);
        jButtonFileLink.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFileLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFileLinkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonFileLink)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCreated)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelDateCreated)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelModified)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelDateModified))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelType)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelID)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(jButtonDelete)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelType)
                            .addComponent(jLabelID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCreated)
                            .addComponent(jLabelDateCreated)
                            .addComponent(jLabelModified)
                            .addComponent(jLabelDateModified)))
                    .addComponent(jButtonDelete, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFileLink)
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        if(Prompts.getUserApproval("Are you sure you want to delete this item?", Prompts.PromptType.QUESTION)){
            item.getFile().delete();
            deleteItem();
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonFileLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFileLinkActionPerformed
        try {
            Desktop.getDesktop().open(item.getFile());
        } catch (IOException ex) {
            thisLog.log(Level.SEVERE, "Unable to open file.", ex);
        }
    }//GEN-LAST:event_jButtonFileLinkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonFileLink;
    private javax.swing.JLabel jLabelCreated;
    private javax.swing.JLabel jLabelDateCreated;
    private javax.swing.JLabel jLabelDateModified;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelModified;
    private javax.swing.JLabel jLabelType;
    // End of variables declaration//GEN-END:variables
}
